# Generated by Django 4.2.1 on 2023-05-31 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("dni", models.IntegerField(unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=30)),
                ("date_of_birth", models.DateField()),
                ("path_license", models.TextField(null=True)),
                ("password", models.CharField(max_length=128)),
                (
                    "saldo",
                    models.DecimalField(decimal_places=4, max_digits=15, null=True),
                ),
                ("CBU", models.IntegerField(null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="api_users",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="api_users",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("passengers_amount", models.IntegerField()),
                ("state", models.CharField(max_length=30)),
                ("opinion", models.CharField(max_length=120, null=True)),
                ("calification", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                ("id_refund", models.IntegerField(primary_key=True, serialize=False)),
                ("percentage", models.IntegerField()),
                ("days_before_trip", models.IntegerField()),
                ("amount", models.DecimalField(decimal_places=4, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name="Transport",
            fields=[
                (
                    "id_transporte",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("patent", models.CharField(max_length=25)),
                ("model", models.CharField(max_length=30)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                ("state", models.CharField(max_length=20)),
                ("fee_passenger", models.DecimalField(decimal_places=4, max_digits=15)),
                ("total_passengers", models.IntegerField()),
                (
                    "transport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.transport"
                    ),
                ),
                (
                    "user_driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id_payment", models.IntegerField(primary_key=True, serialize=False)),
                ("state", models.CharField(max_length=20)),
                ("amount", models.DecimalField(decimal_places=4, max_digits=15)),
                ("datetime", models.DateTimeField()),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.booking"
                    ),
                ),
                (
                    "refund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.refund"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="booking",
            name="trip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.trip"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                fields=("user", "trip"), name="booking_unique_constraint"
            ),
        ),
    ]
