# Generated by Django 4.2.1 on 2023-06-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_trip_transport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
